services:
  - type: web
    name: veridex-shaiksohelll
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /healthz
    autoDeployTrigger: checksPass
    envVars:
      - key: NODE_ENV
        value: production
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_USERNAME
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
